# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import qrcode
import io
from PIL import Image

def generate_qr_code(data, filename="qr_code.png"):
    # Generate QR code
    qr = qrcode.QRCode(version=1, box_size=10, border=5)
    qr.add_data(data)
    qr.make(fit=True)

    # Create an image from the QR code
    img = qr.make_image(fill_color="black", back_color="white")

    # Save the image
    img.save(filename)

    print(f"QR code saved as {filename}")

# Generate QR code for "Hello World"
generate_qr_code("Hello World", "hello_world_qr.png")

